### PR TITLE
WIP: Adding CLI argument option to specify location of settings.yaml

### PR DESCRIPTION
**Pull request by bovem**
Created for the resolution of issue: #45 
Signed by: apal@redhat.com

### CODE REVIEW

**Comment by jyejare** [comment]
Hello @bovem , Is it up for review ?

**Comment by bovem** [comment]
Hi @jyejare sorry for the late reply currently I am occupied with some high priority tasks.

I also wanted to ask that if I am correct the settings file path is currently passed using [this method](https://github.com/RedHatQE/cloudwash/blob/52afd6b42ea4710e4d8b4e104c1abd368b925009/cloudwash/config.py#L10), but if I have passed it as a command line argument then do I have to explicitly define it for individual provider? 
or is there any global way of passing settings file path to all the providers?

**Comment by jyejare** [comment]
Ping @bovem :)

**Comment by bovem** [comment]
Hi, @jyejare 
I had a discussion with @lyfofvipin and @ntkathole regarding the OOP refactoring of the project. But we will need some time to understand the codebase and project in more detail before we can approach that.

**Comment by jyejare** [comment]
@bovem Thanks, I really missed the last comment. Lets setup a meeting next week to talk about that refactor.

**Comment by jyejare** [comment]
@bovem Looks like you need to rebase as the commit history contains the old commits in this PR.

**Comment by bovem** [comment]
> @bovem Looks like you need to rebase as the commit history contains the old commits in this PR.

I see, I did a merge with the master branch of `RedHatQE/cloudwash` repository. Should I do a rebase instead?

**Comment by jyejare** [comment]
Yes @bovem !

**Comment by jyejare** [comment]
Hello @bovem When are you resuming the work. We need not to block this for architectural change to be made as its more of CLI change than an internal.

Could you relook into it and we can get it merged !

**Comment by jyejare** [comment]
Ping @bovem again !!!

**Comment by bovem** [comment]
@jyejare I am sorry I think the PR got closed automatically because I forced pushed some changes to sync it with upstream. I'll raise a new PR with changes.

**Pull request closed without merging**
